/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;


import Lop.DangNhapTK;
import Lop.HoaDonNhap;
import Lop.Sach;
import Table.TableHDNhap;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class QuanLyHoaDonNhap extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    DefaultTableModel hd = null;
    ArrayList<HoaDonNhap> ds = new ArrayList<>();

    /**
     * Creates new form QuanLyHoaDon
     */
    public void layHDN() {
      String filePath = "D:\\hoadon.txt";
    ds.clear(); // Xóa danh sách hiện tại trước khi lấy dữ liệu mới
    
    try {
        File file = new File(filePath);
        Scanner scanner = new Scanner(file);

        while (scanner.hasNextLine()) {
            String line = scanner.nextLine();
            String[] fields = line.split(",");

            if (fields.length == 7) {
                String maHDN = fields[0];
                String maSach = fields[1];
                String maNV = fields[2];
                String ngayNhap = fields[3];
                int soLuongN = Integer.parseInt(fields[4]);
                float donGiaN = Float.parseFloat(fields[5]);
                float thanhTienN = Float.parseFloat(fields[6]);

                HoaDonNhap hd = new HoaDonNhap(maHDN, maSach, maNV, ngayNhap, soLuongN, donGiaN, thanhTienN);
                ds.add(hd);
            } 
        }

        scanner.close();
    } catch (FileNotFoundException e) {
        e.printStackTrace();
    }
    }

    public QuanLyHoaDonNhap() {
        initComponents();
        layHDN();
        loadTable();
    }

    public void loadTable() {
        jtblHoaDonNhap.setModel(new TableHDNhap(ds));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblHoaDonNhap = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jtfMaHD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfMaNV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfNgayLap = new javax.swing.JTextField();
        jtfDonGia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfSoLuong = new javax.swing.JTextField();
        jbtnQuayLai = new javax.swing.JButton();
        jbtnThemHoaDon = new javax.swing.JButton();
        jbtnTimHD = new javax.swing.JButton();
        jcmbMaSach = new javax.swing.JComboBox<>();
        jbtnSua = new javax.swing.JButton();
        jbtnXoa = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("QUẢN LÝ ĐƠN HÀNG");

        jtblHoaDonNhap.setBackground(new java.awt.Color(108, 236, 191));
        jtblHoaDonNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã sách", "Mã nhân viên", "Số lượng", "Đơn giá", "Thành tiền", "Ngày lập"
            }
        ));
        jScrollPane1.setViewportView(jtblHoaDonNhap);
        if (jtblHoaDonNhap.getColumnModel().getColumnCount() > 0) {
            jtblHoaDonNhap.getColumnModel().getColumn(3).setResizable(false);
            jtblHoaDonNhap.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã đơn hàng");

        jtfMaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMaHDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mã nhân viên");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mã sách");

        jtfMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMaNVActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Ngày nhập");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Đơn giá ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Số lượng");

        jbtnQuayLai.setBackground(new java.awt.Color(0, 204, 204));
        jbtnQuayLai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnQuayLai.setText("Quay lại");
        jbtnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnQuayLaiActionPerformed(evt);
            }
        });

        jbtnThemHoaDon.setBackground(new java.awt.Color(102, 255, 255));
        jbtnThemHoaDon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnThemHoaDon.setText("Thêm hóa đơn");
        jbtnThemHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThemHoaDonActionPerformed(evt);
            }
        });

        jbtnTimHD.setBackground(new java.awt.Color(102, 255, 255));
        jbtnTimHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnTimHD.setText("Tìm kiếm");
        jbtnTimHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTimHDActionPerformed(evt);
            }
        });

        jcmbMaSach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03" }));

        jbtnSua.setBackground(new java.awt.Color(51, 255, 255));
        jbtnSua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnSua.setText("Sửa");
        jbtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSuaActionPerformed(evt);
            }
        });

        jbtnXoa.setBackground(new java.awt.Color(51, 255, 255));
        jbtnXoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnXoa.setText("Xóa");
        jbtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnQuayLai)
                .addGap(205, 205, 205)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfMaHD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jtfMaNV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jcmbMaSach, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jbtnThemHoaDon)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jbtnTimHD)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(271, 271, 271))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfSoLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfDonGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnQuayLai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfMaHD)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jtfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmbMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnThemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnTimHD, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(410, 410, 410))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMaNVActionPerformed

    private void jbtnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnQuayLaiActionPerformed
        Menu mn = new Menu();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnQuayLaiActionPerformed
private boolean kiemTraMaHoaDonTonTai(String maHD) {
    for (HoaDonNhap hd : ds) {
        if (hd.getMaHDN().equals(maHD)) {
            return true; // Mã hóa đơn đã tồn tại trong danh sách
        }
    }
    
    String filePath = "D:\\hoadon.txt";
    File file = new File(filePath);
    if (file.exists()) {
        try {
            Scanner scanner = new Scanner(file);
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                String[] fields = line.split(",");
                if (fields.length >= 1 && fields[0].equals(maHD)) {
                    scanner.close();
                    return true; // Mã hóa đơn đã tồn tại trong tệp tin
                }
            }
            scanner.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(QuanLyHoaDonNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    return false; // Mã hóa đơn không tồn tại
}
    private void jbtnThemHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThemHoaDonActionPerformed
        String filePath = "D:\\hoadon.txt";
    
    // Lấy thông tin từ các trường nhập liệu trên giao diện
    String maHD = jtfMaHD.getText();
    String maSach = (String) jcmbMaSach.getSelectedItem();
    String maNV = jtfMaNV.getText();
    String ngayLap = jtfNgayLap.getText();
    int soLuong = Integer.parseInt(jtfSoLuong.getText());
    float donGia = Float.parseFloat(jtfDonGia.getText());
//    float thanhTien = Float.parseFloat(jtfThanhTien.getText());
     float thanhTien = soLuong*donGia;
    // Kiểm tra nếu mã hóa đơn đã tồn tại
    if (kiemTraMaHoaDonTonTai(maHD)) {
        JOptionPane.showMessageDialog(this, "Mã hóa đơn đã tồn tại. Vui lòng chọn mã hóa đơn khác.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return; // Kết thúc hàm nếu mã hóa đơn đã tồn tại
    }
    
    try {
        FileWriter fileWriter = new FileWriter(filePath, true);
        PrintWriter printWriter = new PrintWriter(fileWriter);

        // Kiểm tra nếu tệp tin đã có dữ liệu, thêm ký tự xuống dòng trước khi ghi dữ liệu mới
        File file = new File(filePath);
        if (file.exists() && file.length() > 0) {
            printWriter.println(); // Thêm ký tự xuống dòng
        }

        // Ghi thông tin hóa đơn vào tệp tin
        printWriter.println(maHD + "," + maSach + "," + maNV + "," + ngayLap + "," + soLuong + "," + donGia + "," + thanhTien);

        // Đóng tệp tin
        printWriter.close();
    } catch (IOException ex) {
        Logger.getLogger(QuanLyHoaDonNhap.class.getName()).log(Level.SEVERE, null, ex);
    }

    ds.clear();
    layHDN();
    loadTable();
    }//GEN-LAST:event_jbtnThemHoaDonActionPerformed

    private void jbtnTimHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTimHDActionPerformed
        ArrayList<HoaDonNhap> timKiem = new ArrayList<>();
        for (HoaDonNhap hd : ds) {
            if (jtfMaHD.getText().equals(hd.getMaHDN())) {
                timKiem.add(hd);
            }
        }
        jtblHoaDonNhap.setModel(new TableHDNhap(timKiem));
    }//GEN-LAST:event_jbtnTimHDActionPerformed

    private void jbtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSuaActionPerformed
    String filePath = "D:\\hoadon.txt";
    String maHD = jtfMaHD.getText();
    String maSach = (String) jcmbMaSach.getSelectedItem();
    String maNV = jtfMaNV.getText();
    String ngayLap = jtfNgayLap.getText();
    int soLuong = Integer.parseInt(jtfSoLuong.getText());
    float donGia = Float.parseFloat(jtfDonGia.getText());
     float thanhTien = soLuong*donGia;
    // Đọc tất cả các dòng từ tệp tin và lưu vào danh sách tạm thời
    List<String> lines = new ArrayList<>();
    try (Scanner scanner = new Scanner(new File(filePath))) {
        while (scanner.hasNextLine()) {
            lines.add(scanner.nextLine());
        }
    } catch (FileNotFoundException e) {
        e.printStackTrace();
    }
    
    // Tìm và cập nhật thông tin tài khoản trong danh sách tạm thời
    for (int i = 0; i < lines.size(); i++) {
        String line = lines.get(i);
        String[] fields = line.split(",");
        if (fields.length == 7 && fields[0].equals(maHD)) {
            lines.set(i, maHD + "," + maSach + "," + maNV + "," + ngayLap + "," + soLuong + "," + donGia + "," + thanhTien);
            break;
        }
    }
    
    // Ghi lại tất cả các dòng từ danh sách tạm thời vào tệp tin
    try (PrintWriter writer = new PrintWriter(new FileWriter(filePath))) {
        for (String line : lines) {
            writer.println(line);
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
    
    ds.clear();
    layHDN();
    loadTable();
    
    }//GEN-LAST:event_jbtnSuaActionPerformed
//  columns[0] = jtfMaHD.getText();
//            columns[1] = (String) jcmbMaSach.getSelectedItem();
//            columns[2] = jtfMaNV.getText();
//            columns[3] = jtfNgayLap.getText();
//            columns[4] = jtfSoLuong.getText();
//            columns[5] = jtfDonGia.getText();
//              String maHDNCu = jtfMaHD.getText();
    private void jbtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaActionPerformed
        String filePath = "D:\\hoadon.txt";
    String maHD = jtfMaHD.getText();
    
    // Đọc tất cả các dòng từ tệp tin và lưu vào danh sách tạm thời
    List<String> lines = new ArrayList<>();
    try (Scanner scanner = new Scanner(new File(filePath))) {
        while (scanner.hasNextLine()) {
            lines.add(scanner.nextLine());
        }
    } catch (FileNotFoundException e) {
        e.printStackTrace();
    }
    
    // Xóa thông tin tài khoản trong danh sách tạm thời dựa trên mã nhân viên
    for (int i = 0; i < lines.size(); i++) {
        String line = lines.get(i);
        String[] fields = line.split(",");
        if (fields.length == 7 && fields[0].equals(maHD)) {
            lines.remove(i);
            break;
        }
    }
    
    // Ghi lại tất cả các dòng từ danh sách tạm thời vào tệp tin
    try (PrintWriter writer = new PrintWriter(new FileWriter(filePath))) {
        for (String line : lines) {
            writer.println(line);
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
        ds.clear();
        layHDN();
        loadTable();
    }//GEN-LAST:event_jbtnXoaActionPerformed

    private void jtfMaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMaHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMaHDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDonNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDonNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDonNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDonNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyHoaDonNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbtnQuayLai;
    private javax.swing.JButton jbtnSua;
    private javax.swing.JButton jbtnThemHoaDon;
    private javax.swing.JButton jbtnTimHD;
    private javax.swing.JButton jbtnXoa;
    private javax.swing.JComboBox<String> jcmbMaSach;
    private javax.swing.JTable jtblHoaDonNhap;
    private javax.swing.JTextField jtfDonGia;
    private javax.swing.JTextField jtfMaHD;
    private javax.swing.JTextField jtfMaNV;
    private javax.swing.JTextField jtfNgayLap;
    private javax.swing.JTextField jtfSoLuong;
    // End of variables declaration//GEN-END:variables
}
